---
title: "p8105_hw6_fs2757"
author: "FEI SUN"
date: "2021/12/2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
set.seed(1)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
birthweight_raw = 
  read_csv("data/birthweight.csv") %>% 
  janitor::clean_names()%>% 
  mutate(
    babysex = case_when(babysex == "1" ~ "male",
                        babysex == "2" ~ "female"),
    frace = case_when(frace == "1" ~ "White",
                      frace == "2" ~ "Black",
                      frace == "3" ~ "Asian",
                      frace == "4" ~ "Puerto Rican", 
                      frace == "8" ~ "Other",
                      frace == "9" ~ "Unknown"),
    malform = case_when(malform == "0" ~ "absent",
                        malform == "1" ~ "present"),
    mrace = case_when(mrace == "1" ~ "White",
                      mrace == "2" ~ "Black",
                      mrace == "3" ~ "Asian",
                      mrace == "4" ~ "Puerto Rican",
                      mrace == "8" ~ "Other"),
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace))

skimr::skim(birthweight_raw)

```

```{r}
model1 = lm(bwt ~babysex + bhead + blength + delwt + fincome, data = birthweight_raw)
summary(model1)
broom::tidy(model1)

birthweight_raw %>% 
  modelr::add_residuals(model1) %>% 
  modelr::add_predictions(model1) %>% 
  ggplot(aes(x = pred, y = resid,color=babysex))+
  geom_point(alpha = 0.3)+
  geom_smooth(color = "green",method = "lm", se = F)+
  facet_grid(. ~ babysex)+
  labs(
    x = "Fitted Value",
    y = "Residuals",
    title = "Plot of Residuals against Fitted Value"
  )

```

```{r}
model2 = lm(bwt ~blength + gaweeks, data = birthweight_raw)
summary(model2)
broom::tidy(model2)

```



```{r}
model3 = lm(bwt ~bhead + blength + babysex + 
              bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = birthweight_raw)
summary(model3)
broom::tidy(model3)

```


